// Assuming these headers are for RADSM library                                                                                                                                                                                                                                                                                                                                         
 #include "radsm/Event.h"                                                                                                                                                                                                                                                                                                                                                                
                                                                                                                                                                                                                                                                                                                                                                                         
 class StopwatchStateMachine : public radsm::StateMachine {                                                                                                                                                                                                                                                                                                                              
   // Define your states as members variables                                                                                                                                                                                                                                                                                                                                            
   radsm::State stopped;                                                                                                                                                                                                                                                                                                                                                                 
   radsm::State running;                                                                                                                                                                                                                                                                                                                                                                 
   radsm::State paused;                                                                                                                                                                                                                                                                                                                                                                  
                                                                                                                                                                                                                                                                                                                                                                                         
 public:                                                                                                                                                                                                                                                                                                                                                                                 
   StopwatchStateMachine() :                                                                                                                                                                                                                                                                                                                                                             
      radsm::StateMachine("Stopwatch", &stop),                                                                                                                                                                                                                                                                                                                                           
      // Initializes the states                                                                                                                                                                                                                                                                                                                                                          
      stopped("Stopped"), paused("Paused"), running("Running")                                                                                                                                                                                                                                                                                                                           
   {                                                                                                                                                                                                                                                                                                                                                                                     
       // Add transitions based on events                                                                                                                                                                                                                                                                                                                                                
       // STARTEVENT, PAUSEEVENT, RESUMEEVENT, STOPEVENT are user defined events                                                                                                                                                                                                                                                                                                         
       addTransition(&stopped, STARTEVENT, &running);                                                                                                                                                                                                                                                                                                                                    
       addTransition(&running, PAUSEEVENT, &paused);                                                                                                                                                                                                                                                                                                                                     
       addTransition(&paused, RESUMEEVENT, &running);                                                                                                                                                                                                                                                                                                                                    
       addTransition(&running, STOPEVENT, &stopped);                                                                                                                                                                                                                                                                                                                                     
   }                                                                                                                                                                                                                                                                                                                                                                                     
 };                                                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                         
 int main() {                                                                                                                                                                                                                                                                                                                                                                            
   StopwatchStateMachine stopwatch;                                                                                                                                                                                                                                                                                                                                                      
                                                                                                                                                                                                                                                                                                                                                                                         
   stopwatch.process_event(STARTEVENT);                                                                                                                                                                                                                                                                                                                                                  
   std::this_thread::sleep_for(std::chrono::seconds(2));                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                         
   stopwatch.process_event(PAUSEEVENT);                                                                                                                                                                                                                                                                                                                                                  
   std::this_thread::sleep_for(std::chrono::seconds(1));                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                         
   stopwatch.process_event(RESUMEEVENT);                                                                                                                                                                                                                                                                                                                                                 
   std::this_thread::sleep_for(std::chrono::seconds(3));                                                                                                                                                                                                                                                                                                                                 
                                                                                                                                                                                                                                                                                                                                                                                         
   stopwatch.process_event(STOPEVENT);                                                                                                                                                                                                                                                                                                                                                   
                                                                                                                                                                                                                                                                                                                                                                                         
   return 0;                                                                                                                                                                                                                                                                                                                                                                             
 }                     